# This file was generated by GoReleaser. DO NOT EDIT.
cask "antenne" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "c1aeaae5586bfbfe3538ab2416158a078c6e454c08bf49058a2d60a3e677b687"
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v#{version}/antenne-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "91ed14c958b7ab0c6692cb271e3fa12492862b763b51097b131f4604a795de28"
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v#{version}/antenne-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "fb2402eaa377e368fbf03b6e357d0b27143623c5640ec382d34e5de973803926"
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v#{version}/antenne-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "76df1391b7ab937eeee40f0e1d2db18f4094514cc55ccd9f65bddbd089834b3a"
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v#{version}/antenne-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "antenne"
  desc "Terminal client for an Antenne instance, the alert bus"
  homepage "https://github.com/FacileStudio/antenne-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antenne"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antenne"]
    end
  end

  # No zap stanza required
end
