# This file was generated by GoReleaser. DO NOT EDIT.
cask "antenne" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "9b4a53032a29f8fa4d6d830424f48143b73bfdcf91686bb60e7f1e9d6e25d742"
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v#{version}/antenne-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_arm do
      sha256 "6cf1471582389f5f30fd16ddce59da35289dd5e62e8ed0875b0216e9b2d5dd32"
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v#{version}/antenne-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  on_linux do
    on_intel do
      sha256 "618fbf9286c73521812debeba99bee88ae016bad8acb0be4024099da213044c9"
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v#{version}/antenne-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_arm do
      sha256 "14433979b0734a7d0bac18810854fef8b38821072655dbb84ae596c582a9e379"
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v#{version}/antenne-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "antenne"
  desc "Terminal client for an Antenne instance, the alert bus"
  homepage "https://github.com/FacileStudio/antenne-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "antenne"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/antenne"]
    end
  end

  # No zap stanza required

end
