# This file was generated by GoReleaser. DO NOT EDIT.
cask "bulle" do
  version "0.81.0"

  on_macos do
    on_arm do
      sha256 "e7c784e5a090f2a97f93f5341ad066828bcb2e10b82016be301ad55bf752632c"
      url "https://github.com/FacileStudio/bulle/releases/download/v#{version}/bulle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3f73bff0cb16f0a416d4257beda89d00cc9fb40e5e84de4492af14f3356793ca"
      url "https://github.com/FacileStudio/bulle/releases/download/v#{version}/bulle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "278beb7054038b0629d72ab1f69f9b02b5dba086e9918ec4c2473f1996405e5d"
      url "https://github.com/FacileStudio/bulle/releases/download/v#{version}/bulle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "11c0d8101f351510b3270a7d0411c671d57ca232d407fefe96da9ca91a8995a3"
      url "https://github.com/FacileStudio/bulle/releases/download/v#{version}/bulle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bulle"
  desc "Terminal coding agent — the human harness for the bulle SDK"
  homepage "https://github.com/FacileStudio/bulle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bulle"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bulle"]
    end
  end

  # No zap stanza required
end
