# This file was generated by GoReleaser. DO NOT EDIT.
cask "bulle" do
  version "0.83.0"

  on_macos do
    on_arm do
      sha256 "9f99df2ce132c793862b07adda7479b3c714d1c7741efdbf567b83c312081f95"
      url "https://github.com/FacileStudio/bulle/releases/download/v#{version}/bulle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "21996da835622b02aabc19eb7cc846fe2b2f30cd1230fa5f9493c9a4b6aa3be9"
      url "https://github.com/FacileStudio/bulle/releases/download/v#{version}/bulle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "170087e485f0dc3a06abebc01c66ecb59873e559ab336bd71dbcb91520112f71"
      url "https://github.com/FacileStudio/bulle/releases/download/v#{version}/bulle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d8d32628011cb81d4ed3156642732621dfa8cb92143671f300576f6d23323eb5"
      url "https://github.com/FacileStudio/bulle/releases/download/v#{version}/bulle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bulle"
  desc "Terminal coding agent — the human harness for the bulle SDK"
  homepage "https://github.com/FacileStudio/bulle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bulle"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bulle"]
    end
  end

  # No zap stanza required
end
