# This file was generated by GoReleaser. DO NOT EDIT.
cask "capsule" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "2091e2b5c88a57111c602a88f6663c7a765d3cd7f5ebf62b6c266335135b5a64"
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v#{version}/capsule-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_arm do
      sha256 "c4804154bde17d5fef9c7707214a074f9732a94fb0ae9b5c340e920b44717433"
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v#{version}/capsule-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  on_linux do
    on_intel do
      sha256 "d029a9c0caa58d24289bc1c201822067b8a3a85997059f267f21b21badfabe30"
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v#{version}/capsule-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_arm do
      sha256 "04d7d1dfb9f11deae27592fc676eb484d2cf2fdbaf57b03812a02f40a3188962"
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v#{version}/capsule-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "capsule"
  desc "Terminal client for Capsule, the zero-knowledge encrypted paste service"
  homepage "https://github.com/FacileStudio/capsule-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capsule"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capsule"]
    end
  end

  # No zap stanza required

end
