# This file was generated by GoReleaser. DO NOT EDIT.
cask "capsule" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "4ed48953ba38dbcca8380c59cdbad9636a8da54628cde0834f494721cbeed594"
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v#{version}/capsule-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "0dd5d81bc7a893a3a40b539fe1d03ea2e760e9e7df9bc05bc892962d65c10a15"
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v#{version}/capsule-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "c5adc01d80fdab10a41ac1f323d09b15e6792d69baa504efe2922e4f53c012cb"
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v#{version}/capsule-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "af431478b479e6bc08b28448a3c4845611184494a34542633cf0c8401937efcc"
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v#{version}/capsule-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "capsule"
  desc "Terminal client for Capsule, the zero-knowledge encrypted paste service"
  homepage "https://github.com/FacileStudio/capsule-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capsule"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capsule"]
    end
  end

  # No zap stanza required
end
