# This file was generated by GoReleaser. DO NOT EDIT.
cask "courrier" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "ee569ec0ce48e852e81d786e700c26e73f0e2893c76d95b0f92f344c6c339e14"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "98400fb59cedf2d8d0b2f7430f0514fb77df4a5a06fcac34c0d31798c9b4d852"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "90b69f38510dd0a9ca6430bb6f38a67903be0c49b6d5da958f74534b13b5107b"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "5ae6acc24b1db02fcc6cd07c46f2333cf8715117aca10f3f13db588dc6daca2e"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "courrier"
  desc "Terminal client for Courrier, the suite's self-hosted email service"
  homepage "https://github.com/FacileStudio/courrier-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courrier"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/courrier"]
    end
  end

  # No zap stanza required
end
