# This file was generated by GoReleaser. DO NOT EDIT.
cask "courrier" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "7f1b7a9fb4540390c275806d2c70ebb405b047aea3b62f470f2fcad27efa3b69"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_arm do
      sha256 "fe5461b245bacd349b6f3eec0cbd045564f40908abc31fcbc6f304f00e143e69"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d99174c7927d89b82ba337b9f6510f0fc9539728c2b2cd6294a935929367026"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_arm do
      sha256 "781b43f888b9b1cf6fc663564183f39ff1c320ed7a69e69943c02b13bd1b4c1a"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "courrier"
  desc "Terminal client for Courrier, the suite's self-hosted email service"
  homepage "https://github.com/FacileStudio/courrier-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courrier"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/courrier"]
    end
  end

  # No zap stanza required

end
