# This file was generated by GoReleaser. DO NOT EDIT.
cask "courrier" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "13f3640b9f23c655ca5767e3f3540427050ed4336d50509ff2c753fb98e66a48"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "96e7f24539b8a825d6b9551c1bddfb6045bd92f81d568e94122610fa5182b0f6"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "c75bcc9dbf741c30666fc97ec4db096b84b1df9fa64ba1fd2e9b383718ef2062"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "4be11dcd6dd854016db105ea7b7d7c918de0871406e6590087e0098960d61fca"
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v#{version}/courrier-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "courrier"
  desc "Terminal client for Courrier, the suite's self-hosted email service"
  homepage "https://github.com/FacileStudio/courrier-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courrier"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/courrier"]
    end
  end

  # No zap stanza required
end
