# This file was generated by GoReleaser. DO NOT EDIT.
cask "douane" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "71c8fb73d151e37d53dbe6828bd1fe73218ec15f07127971d192470c3c80b443"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4ff072da97d098d0ba71136279de370ec149c7046971229b038489f551851f09"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c3775931bebc147b668afd692708516f6920a073bbb2a725ca78f17eae5dc823"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8eda36fae11d0c36411f919d47a59f03efd3ceb0ce0ff8b88434dbeefcdfd7db"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_linux_amd64.tar.gz"
    end
  end

  name "douane"
  desc "Vulnerability sweep for the Facile Studio suite"
  homepage "https://github.com/FacileStudio/douane"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "douane"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/douane"]
    end
  end

  # No zap stanza required
end
