# This file was generated by GoReleaser. DO NOT EDIT.
cask "douane" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "cf345e93231462b596643a4d8ae94c75104f72b0e6a5203a7564af96022e95b5"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e27a9238b376d327f8e61f6b923bc2967b1ce0900c4115f19dccdfc62a2d878"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9b730d1415c70b51679fa5611eab7a469a368a2d505adf46b19516b33b4e6f48"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "056d40286afcca96c1389ef60d03821cecf7ec4d9c9b13484e8303c1e35ea799"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_linux_amd64.tar.gz"
    end
  end

  name "douane"
  desc "Vulnerability sweep for the Facile Studio suite"
  homepage "https://github.com/FacileStudio/douane"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "douane"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/douane"]
    end
  end

  # No zap stanza required
end
