# This file was generated by GoReleaser. DO NOT EDIT.
cask "douane" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "7f6c819874e90ee6228ad3978185106da0647be5499ea68632b61b7b108de478"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "019120b000397f7148672bb6b4e0b23f086aa71065885eca09b5f8451f2d0334"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a5b3559b3f7b73043aef268fe1a1dbd2eabd94f58f33495e3f17890191281348"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "db417299659f7705fd248e417f88ad8deb416446ea95a25a15b588c30aae3081"
      url "https://github.com/FacileStudio/douane/releases/download/v#{version}/douane_#{version}_linux_amd64.tar.gz"
    end
  end

  name "douane"
  desc "Vulnerability sweep for the Facile Studio suite"
  homepage "https://github.com/FacileStudio/douane"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "douane"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/douane"]
    end
  end

  # No zap stanza required
end
