# This file was generated by GoReleaser. DO NOT EDIT.
cask "facile" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "1ced67e9641616b140733a07dccc1b3818e5077c5008fece0c23da4dce299c8f"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "9e62826f147612782bac254d3efd08578520a0b225bb1ad8213f2b0751e90d50"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "0d523aec1b10e414a9c7a0dcf63431d8488b99e42f6f11b2f7cbcca52d2cfe0d"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "765e2b08140b931eda98475438ae5fa77bf14c69eb154178a7280debf8de7794"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "facile"
  desc "One installer for the whole Facile Studio suite"
  homepage "https://github.com/FacileStudio/facile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "facile"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/facile"]
    end
  end

  # No zap stanza required
end
