# This file was generated by GoReleaser. DO NOT EDIT.
cask "facile" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "d3e109ec915015724d3fe4efc3cda351d2bb9320878cb7e6416d5b44ef7748bb"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "184042f66a038b415d6984f636ca28f0804c72bbc324686d712a73fccb13ffee"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "e654c3e3a61ecc46325f419211711d5e56d993b55c5b88ceaa9bb8e7e736814e"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "cacbe4a37b4ea67124455d687482fea592f92ad4e96933762ff9f2fa27bec96d"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "facile"
  desc "One installer for the whole Facile Studio suite"
  homepage "https://github.com/FacileStudio/facile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "facile"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/facile"]
    end
  end

  # No zap stanza required
end
