# This file was generated by GoReleaser. DO NOT EDIT.
cask "facile" do
  version "0.15.3"

  on_macos do
    on_arm do
      sha256 "c22ea1a13b8c69b97d464858621e0a97c7ec1d92c254013cbed2f8c09267c991"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "58d3f20323cd25a095f3b5d933bf585d58485de00d67cf0d6d1d774050049987"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "98a87a19f08a92c77cc1f723b04a44cb874b558f3df70b695e793f83032eab38"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e55246d02e44897939666636404c8480372ad76aef3f7e284642a3f1261019f4"
      url "https://github.com/FacileStudio/facile/releases/download/v#{version}/facile_#{version}_linux_amd64.tar.gz"
    end
  end

  name "facile"
  desc "One installer for the whole Facile Studio suite"
  homepage "https://github.com/FacileStudio/facile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "facile"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/facile"]
    end
  end

  # No zap stanza required
end
