# This file was generated by GoReleaser. DO NOT EDIT.
cask "filet" do
  version "0.13.1"

  on_macos do
    on_arm do
      sha256 "c4af14b8669cac01f2c8b6a24ccab51328dfe4854f16769ee808c39bc6c6b1a8"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "85faca997e09ce9df6c046ddd327d98d7ca79d34bed8b1c2cea5df569d88e899"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8a4136b97ab9079b7f53dadac0a6785099306bf4a7896a1e59a9521620be3bab"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d8304ae5959c84378ffa47035228f78e7fac4bd875fd47ea4967689a669b0197"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "filet"
  desc "Code-quality checker enforcing the Facile team guidelines"
  homepage "https://github.com/FacileStudio/filet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filet"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/filet"]
    end
  end

  # No zap stanza required
end
