# This file was generated by GoReleaser. DO NOT EDIT.
cask "filet" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "b142abc9e54aa5d071cfc106ea70bbeebd3758f3ec060bbf234c76a83dda1515"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "abe5d4d2733bf5535b0cff5cf56723cfee3163ddc76670864179e610d5e80ab7"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5507238443b3d14174cce903b040309128091d94016cb797b70ff3e85d329ae3"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "99202ecfe794f477c69f855c1d9158e9a99d1be76ad293968bfe8a490f756da9"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "filet"
  desc "Code-quality checker enforcing the Facile team guidelines"
  homepage "https://github.com/FacileStudio/filet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filet"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/filet"]
    end
  end

  # No zap stanza required
end
