# This file was generated by GoReleaser. DO NOT EDIT.
cask "filet" do
  version "0.18.1"

  on_macos do
    on_arm do
      sha256 "e624adad7a10c7225f676b3825f51c2c272bcb352524329695075c48e8e143fe"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4ede464b8fb1f38382eb11f81275f55d48e670a26f02501d53f97bbe3e61c837"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4ed9c019e4ceb04c799431f30dfe337016748ef59e4a36c3433913794b1086e9"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "be3b3359c8051fd354058a1cb6d03977e130bb1e44317717b2c79304449ee1ab"
      url "https://github.com/FacileStudio/filet/releases/download/v#{version}/filet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "filet"
  desc "Code-quality checker enforcing the Facile team guidelines"
  homepage "https://github.com/FacileStudio/filet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filet"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/filet"]
    end
  end

  # No zap stanza required
end
