# This file was generated by GoReleaser. DO NOT EDIT.
cask "journal" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "61164ee2968ca526f1f3057d4f259251ee869f9f8619219f6751b0c90c1a7fa7"
      url "https://github.com/FacileStudio/journal-cli/releases/download/v#{version}/journal-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "e7a64f72e6967ded99e01edd7270b9e47ffa3c44abeb749830c4bf2641b0694e"
      url "https://github.com/FacileStudio/journal-cli/releases/download/v#{version}/journal-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "e615c6416f4f2d011921b2ccfa6dee7297de862e873e7d7d430a9ad2bb718bba"
      url "https://github.com/FacileStudio/journal-cli/releases/download/v#{version}/journal-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "a77dbb91151a4a47fa99cff3861553671a66dc09b400518f682aefcdc369f9d0"
      url "https://github.com/FacileStudio/journal-cli/releases/download/v#{version}/journal-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "journal"
  desc "Terminal client for Journal, the suite's centralized logging service"
  homepage "https://github.com/FacileStudio/journal-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "journal"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/journal"]
    end
  end

  # No zap stanza required
end
