# This file was generated by GoReleaser. DO NOT EDIT.
cask "journal" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "614c3d70e9419f96eb8ffe14dba80f3787cb29181e7b8179f493a681c26af9c0"
      url "https://github.com/FacileStudio/journal-cli/releases/download/v#{version}/journal-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "e92dd2b20d5924d4231e846a2a74a14aa8f772a0d95dae3df593e386ab4af881"
      url "https://github.com/FacileStudio/journal-cli/releases/download/v#{version}/journal-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "3e9dcaa5c517dcc9467af0de336034033e20e26a3ffa85f90ee4815373293bb0"
      url "https://github.com/FacileStudio/journal-cli/releases/download/v#{version}/journal-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "1374cc896e0ff0d689ec25c9ce7d1370c86dc57669e969f47ab615f797995918"
      url "https://github.com/FacileStudio/journal-cli/releases/download/v#{version}/journal-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "journal"
  desc "Terminal client for Journal, the suite's centralized logging service"
  homepage "https://github.com/FacileStudio/journal-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "journal"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/journal"]
    end
  end

  # No zap stanza required
end
