# This file was generated by GoReleaser. DO NOT EDIT.
cask "kori" do
  version "0.67.1"

  on_macos do
    on_arm do
      sha256 "978bd374c7c8bfe84e2b2bd2ebfe89db028d8679fae73ccdca19c941232a7c7d"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "86d71dd84b4441d808c2f803ec100bc7aa36685b93c1432240284e929ebe5e23"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "80beea7b0bea48b6c68919d0198e505df72d1bc6951af4514461dafdb8b251ba"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ede9f7a5677eff278e2cc1d7de179abb98c86ffbbc3fcde40ff5b90fc9c202a9"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kori"
  desc "Terminal coding agent — the human harness for the kori SDK"
  homepage "https://github.com/FacileStudio/kori"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kori"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kori"]
    end
  end

  # No zap stanza required
end
