# This file was generated by GoReleaser. DO NOT EDIT.
cask "kori" do
  version "0.65.0"

  on_macos do
    on_arm do
      sha256 "f9f90fa9f61eddd2cb3d863c2123b15967d879f481821beb6fc11ab960273b54"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b50e0d9c4cf6391985cc54b28d0f56b72344cf45e070849c02c39d931009b9d"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4b7bd07e64f6734fa325dc50e2c160032ba529dece5205e658d8fdc4d1c72281"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cba7b026b00bbe9ad5c002bd52f07f4c2c52b191077ea6984d94a137fa0cbc86"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kori"
  desc "Terminal coding agent — the human harness for the kori SDK"
  homepage "https://github.com/FacileStudio/kori"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kori"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kori"]
    end
  end

  # No zap stanza required
end
