# This file was generated by GoReleaser. DO NOT EDIT.
cask "kori" do
  version "0.61.1"

  on_macos do
    on_arm do
      sha256 "2a162862a3c6ab13fcf9f966831faba3c92bef4ba66785576f55ec0fcd193bf7"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1d501e3a344a6aa31b58dd0b5315a476cd3a32c779029a2308bb86b5894d39e"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "44ff99b6576bd9f579f1eb2e64544576f3c0f94456ad5b872b7578054e9328ea"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ebb472f424c9897f8b66e66ce5af7acfe180cb10465d40e6696c6479600b261"
      url "https://github.com/FacileStudio/kori/releases/download/v#{version}/kori_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kori"
  desc "Terminal coding agent — the human harness for the kori SDK"
  homepage "https://github.com/FacileStudio/kori"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kori"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kori"]
    end
  end

  # No zap stanza required
end
