# This file was generated by GoReleaser. DO NOT EDIT.
cask "mycelium" do
  version "0.34.0"

  on_macos do
    on_arm do
      sha256 "32c828d1e3573d4a08c3e5c630acf5c27b76f964325341f33c0de9cb1693ae39"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7514c989bbd4e701d8211ca481e1903a4352acdf17dbf07395f93307d9c2fcf4"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8b62df3470f06f68b3402a235297d9cee638eb0a83b0736c734c9a76240155ed"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "658a61689a65f2bc73943bae069e33dfc821e946ee64ac7466e60e1d474bd54a"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mycelium"
  desc "Shared agent memory across AI coding agents and machines"
  homepage "https://github.com/FacileStudio/Mycelium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mycelium"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mycelium"]
    end
  end

  # No zap stanza required
end
