# This file was generated by GoReleaser. DO NOT EDIT.
cask "mycelium" do
  version "0.35.0"

  on_macos do
    on_arm do
      sha256 "b736352d8f26dfc672b3e5a77b88da018c77bc853947e94e172967c96d911069"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0d7a25839a47909e00528c0dc1a4d1974404f511eedd04cd8147e12600e74630"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "11f5e973a4a46e4fcdb90fce146d78c6abd9dcf0255b220366e179baef1a0e0e"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "11906b61f8b34858982b6ed412e3d55e7ab2875369eef578cb37e151676190b3"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mycelium"
  desc "Shared agent memory across AI coding agents and machines"
  homepage "https://github.com/FacileStudio/Mycelium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mycelium"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mycelium"]
    end
  end

  # No zap stanza required
end
