# This file was generated by GoReleaser. DO NOT EDIT.
cask "mycelium" do
  version "0.31.0"

  on_macos do
    on_arm do
      sha256 "a129180b950537781fa7063a38d0bdee5f7ff3c55de22d70808f96e2a72e86b2"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "1c0ffd5b6dc41bdaf238b8c5cf17b9e23cda4a71be51b8fdf44df7346c6326e9"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "26bf2ffae9e8cc5458a14dccbc23a2dae59118d41caae47ddc8236529e5bbfc5"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "cfb8f650399d4f097751dbec084d69524df5e7588f5f25464edef30b68488b0a"
      url "https://github.com/FacileStudio/Mycelium/releases/download/v#{version}/Mycelium_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "mycelium"
  desc "Shared agent memory across AI coding agents and machines"
  homepage "https://github.com/FacileStudio/Mycelium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mycelium"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mycelium"]
    end
  end

  # No zap stanza required
end
