# This file was generated by GoReleaser. DO NOT EDIT.
cask "nacelle" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "4753c050b75291d565b4c3eaf422b0010a2ae56a218b89f97548169fbd66aaf1"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "59e05f5464d3258153f322d1300ac012b275afc8b227cd893f0a6856c46ee47c"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "cb91a87317f98a0702a84accb5b4028981fa35315664064232b6e68457ffa2bd"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "b6707240d1ecb4e714c5b36a33780e473d544ca6f8e2414c7de9191be97a8b88"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "nacelle"
  desc "Terminal coding agent — the human harness for the nacelle SDK"
  homepage "https://github.com/FacileStudio/nacelle-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nacelle"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nacelle"]
    end
  end

  # No zap stanza required
end
