# This file was generated by GoReleaser. DO NOT EDIT.
cask "nacelle" do
  version "0.53.1"

  on_macos do
    on_arm do
      sha256 "335ab03161f642f0ee84e53e4b1c8e089989b94cbb09a25f6856541f1db16f7f"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd04e6f08cc2c3f60e59fd6144659f798482acd4c4fbca5c1be36f7c85220a71"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f421d907e9e1473464975d5abf5d25e987f98b930668d415d60c4d0b0f7e09a1"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4628e39c2695da54fdd71296b672fe1a6669b11e5cc651617189a4a4cd73abbc"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nacelle"
  desc "Terminal coding agent — the human harness for the nacelle SDK"
  homepage "https://github.com/FacileStudio/nacelle-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nacelle"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nacelle"]
    end
  end

  # No zap stanza required
end
