# This file was generated by GoReleaser. DO NOT EDIT.
cask "nacelle" do
  version "0.53.7"

  on_macos do
    on_arm do
      sha256 "4c6c12157159565641cf0db020775768c8ff74d797644060332764f22d932f47"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c2c65e6c8afb67babb6aed800988551e4f70492db921261ae307a9e6f5dc779a"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0637c3887f0385a303c44ba599247ac469291df5d00aa9ee295220c62b5e2cab"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff1a85aa49e4a5662484c01caf01c4a7c811177d9dc597afeb4236b921aa6215"
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v#{version}/nacelle-tui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nacelle"
  desc "Terminal coding agent — the human harness for the nacelle SDK"
  homepage "https://github.com/FacileStudio/nacelle-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nacelle"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nacelle"]
    end
  end

  # No zap stanza required
end
