# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonar" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "72ab25229e3b0dc183d4f582fb0b6f07c5351d4aab74f9f2c933e2b1b8caca1b"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "396057102cfc02a714bebbd6ee6c167e9db5776125580754a54b73befb052b60"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "31b5beee10bcd74f7e2a02c5853cf7e207df7a7c30e304ba827e1282f315a718"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "23c96cbc172a5fafc899ecc1323316890657ea43557bd27930144b10841ef766"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sonar"
  desc "Multi-engine web search for the terminal"
  homepage "https://github.com/FacileStudio/sonar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonar"]
    end
  end

  # No zap stanza required
end
