# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonar" do
  version "0.5.2"

  on_macos do
    on_arm do
      sha256 "11611706df73ac5566550a60ef0006d8d7c9b82e8a68a176f6bb76f62aeeb2c1"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bb960cb8bcd8608169f2228d093c3af7db1bf17305e086941aebd93dea49a8d4"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a6fe91533c0aa263b19e7af49b29308c9836abcc5f10ccd318a57a8e07e48111"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "639c3dfa01632bd83772358bf6703770947b841ea510f1b247d8b68422e41d01"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sonar"
  desc "Multi-engine web search for the terminal"
  homepage "https://github.com/FacileStudio/sonar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonar"]
    end
  end

  # No zap stanza required
end
