# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonar" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "0a993bd9f1e430056398df304937360a9d89533664ae4ec953fe18af33e5a603"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "efc0f21e9fa642b67d4b79e3b64f75070323fec954d81a6a045e3be2c42e1c69"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5e224a8da9ee64ab4304e3ef8cafca269a7f4f7894d49c31900f66c2957fd79c"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1fc299813446c9e2e27ab0c242568837dcb58fa6115d151f3df8d250d513d695"
      url "https://github.com/FacileStudio/sonar/releases/download/v#{version}/sonar_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sonar"
  desc "Multi-engine web search for the terminal"
  homepage "https://github.com/FacileStudio/sonar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonar"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonar"]
    end
  end

  # No zap stanza required
end
