# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonde" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "66933eb8663d8411678cb59daacdd0a835bf9bec7c17d08173674d31e5a6bd7c"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "abb5ed4af9e9af5df4e65d39a6f8becea5ebec3ca976365cd858829a19f17dc5"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "aebd6bed0a7af52d9a261680f4356ee7126553a4a40a4191e0978624c96f516c"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "5ab15f23a267833516178224bb026ca486545b222e05959b7eff8775f02addd4"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "sonde"
  desc "Terminal client for Sonde, the suite's self-hosted uptime monitor"
  homepage "https://github.com/FacileStudio/sonde-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonde"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonde"]
    end
  end

  # No zap stanza required
end
