# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonde" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "434ccf5654b626d57bf79d9f5905842ef4bd84e8fa1af9312763be728643c9a5"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "87c5240b4a28dac0198e742dc7f1186744c4fdf27926c606b2136fd8aabc8c2c"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "4f5861425d32f52cf2905d70fae690a95e1e34f9c4bd288ce7b9bf02ffe6f210"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "b9500921c611774bda4c74e278c67ffd3cd194ad36da32ff432fe536824f2db6"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "sonde"
  desc "Terminal client for Sonde, the suite's self-hosted uptime monitor"
  homepage "https://github.com/FacileStudio/sonde-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonde"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonde"]
    end
  end

  # No zap stanza required
end
