# This file was generated by GoReleaser. DO NOT EDIT.
cask "sonde" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "0a46d54248ac574a58be681a9552b91a2e27d1c3cf55c8a6a1952b7489eb43ed"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "17bd7dfe4c06399959ebb2d0b30311288c8f4a0e84d03185d5af3016bc1b8bbc"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end
  on_linux do
    on_arm do
      sha256 "18c01acfa3a59f549a91561ef3428f3249f45e7f0fd396ac86d5f2ad48ef56a3"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
    on_intel do
      sha256 "d8bbaed69dd4f1d746171084b26c017cc10e5e46870e990c33da5d96c9e4432d"
      url "https://github.com/FacileStudio/sonde-cli/releases/download/v#{version}/sonde-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/FacileStudio/"
    end
  end

  name "sonde"
  desc "Terminal client for Sonde, the suite's self-hosted uptime monitor"
  homepage "https://github.com/FacileStudio/sonde-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sonde"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sonde"]
    end
  end

  # No zap stanza required
end
