# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antenne < Formula
  desc "Terminal client for an Antenne instance, the alert bus"
  homepage "https://github.com/FacileStudio/antenne-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v0.2.0/antenne-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "4491aac7bdc175763f687d06cb49370afdc669fd678eb1cf95b424c863200440"

      define_method(:install) do
        bin.install "antenne"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v0.2.0/antenne-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "99168878a4a4fda93ebbaaf0d8a6d8fc701db2bf31d5bf7a4a5c16068c70b81f"

      define_method(:install) do
        bin.install "antenne"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v0.2.0/antenne-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "058409afc25af802cb2cdf38253f9f6f91e8b536f0140a36b2c8a19353760db0"
      define_method(:install) do
        bin.install "antenne"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/antenne-cli/releases/download/v0.2.0/antenne-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "ce71998950be8a1a001cb96b1e9ee7894febcac2d6af20ea4702e3cf233a4fa0"
      define_method(:install) do
        bin.install "antenne"
      end
    end
  end

  test do
    system "#{bin}/antenne", "--version"
  end
end
