# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Capsule < Formula
  desc "Terminal client for Capsule, the zero-knowledge encrypted paste service"
  homepage "https://github.com/FacileStudio/capsule-cli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v0.1.2/capsule-cli_0.1.2_darwin_amd64.tar.gz"
      sha256 "4901a1f068b2b1e3b3abb51fada5afacfcad528984613971fbe2e22afbc67f68"

      define_method(:install) do
        bin.install "capsule"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v0.1.2/capsule-cli_0.1.2_darwin_arm64.tar.gz"
      sha256 "99d4e4ce7f75c1a7e674bb5bea31383946becdd26b46e6feb250387830f8dc4f"

      define_method(:install) do
        bin.install "capsule"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v0.1.2/capsule-cli_0.1.2_linux_amd64.tar.gz"
      sha256 "cd72f3dac72de300b8d76ab58a4c1c3a9f73ac4c35d8207cb15802e4ab3260bf"
      define_method(:install) do
        bin.install "capsule"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/capsule-cli/releases/download/v0.1.2/capsule-cli_0.1.2_linux_arm64.tar.gz"
      sha256 "3545bc2557d80057af882894f4bee1c6b03d6f4156f6ec726cc007bf11618c39"
      define_method(:install) do
        bin.install "capsule"
      end
    end
  end

  test do
    system "#{bin}/capsule", "--version"
  end
end
