# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Courrier < Formula
  desc "Terminal client for Courrier, the suite's self-hosted email service"
  homepage "https://github.com/FacileStudio/courrier-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v0.1.1/courrier-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "d4f3ecdc93879fde7bf838ee35729da3ac631d5e4f2fa3e9681198ccba371af5"

      define_method(:install) do
        bin.install "courrier"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v0.1.1/courrier-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "aebd72a6b8733144b54dbeb5fb6ae057005a28b54af5724da133e24945c86496"

      define_method(:install) do
        bin.install "courrier"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v0.1.1/courrier-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "8cec1609e534cafdb5000e37d433a4b7fc3e02c30c38135e830042e1f0d6971f"
      define_method(:install) do
        bin.install "courrier"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/courrier-cli/releases/download/v0.1.1/courrier-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "afa76092533eb038c411f93d8a62f77bc2e69a7e2d30bf816cd0c265d48cdf66"
      define_method(:install) do
        bin.install "courrier"
      end
    end
  end

  test do
    system "#{bin}/courrier", "--version"
  end
end
