# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Facile < Formula
  desc "One installer for the whole Facile Studio suite"
  homepage "https://github.com/FacileStudio/facile"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/facile/releases/download/v0.6.1/facile_0.6.1_darwin_amd64.tar.gz"
      sha256 "d67735dc010840f477cc83b08a3b8013cc916eeb724e94e4a46fc1381af8b464"

      define_method(:install) do
        bin.install "facile"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/facile/releases/download/v0.6.1/facile_0.6.1_darwin_arm64.tar.gz"
      sha256 "27d16f99e3f94eab61d002069a140e0f13c3f6d38aa2450033823af0bd81258e"

      define_method(:install) do
        bin.install "facile"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/facile/releases/download/v0.6.1/facile_0.6.1_linux_amd64.tar.gz"
      sha256 "05756b6671bd382752a2e2575fc04ed4d376f93188ec5fd6dbcf2b1b24d5de94"
      define_method(:install) do
        bin.install "facile"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/facile/releases/download/v0.6.1/facile_0.6.1_linux_arm64.tar.gz"
      sha256 "eb4172571022643e00e33b723c511f254858a164846bb3da2fe2314ca2925e91"
      define_method(:install) do
        bin.install "facile"
      end
    end
  end

  test do
    system "#{bin}/facile", "--version"
  end
end
