# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Journal < Formula
  desc "Terminal client for Journal, the suite's centralized logging service"
  homepage "https://github.com/FacileStudio/journal-cli"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/journal-cli/releases/download/v0.2.1/journal-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "c0ebedcbd17377e658e055383dfb337801a401c948c91759daa17b1f6f786c92"

      define_method(:install) do
        bin.install "journal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/journal-cli/releases/download/v0.2.1/journal-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "013c1fe4dfd9d939d97f476f95bd7344fa6e7b8fe1ad26cb18a5d4ef97cad58f"

      define_method(:install) do
        bin.install "journal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/journal-cli/releases/download/v0.2.1/journal-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "18d5948160f9e5ba8d9134db15e9f386ab03d7e60efbf23ccd000008da98d7e6"
      define_method(:install) do
        bin.install "journal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/journal-cli/releases/download/v0.2.1/journal-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "8c0410c745332edc7c40af39bb61f0f3e9a474547799b961ae032a5d2a1ea32e"
      define_method(:install) do
        bin.install "journal"
      end
    end
  end

  test do
    system "#{bin}/journal", "--version"
  end
end
