# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mycelium < Formula
  desc "Shared agent memory across AI coding agents and machines"
  homepage "https://github.com/FacileStudio/Mycelium"
  version "0.21.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.21.0/Mycelium_0.21.0_darwin_amd64.tar.gz"
      sha256 "f38b7ddf42a4556f7ab231361c080a16f319a3f95bd5472b09d4fe77a5a63c03"

      define_method(:install) do
        bin.install "mycelium"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.21.0/Mycelium_0.21.0_darwin_arm64.tar.gz"
      sha256 "9a40cc1966178cec9f8763dde782794515e8aa5051d7ab3f2ec32628d8b6b587"

      define_method(:install) do
        bin.install "mycelium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.21.0/Mycelium_0.21.0_linux_amd64.tar.gz"
      sha256 "83959ad3212dd380c76c497cd6cc62f95e9476367652129364839813cf89097b"
      define_method(:install) do
        bin.install "mycelium"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.21.0/Mycelium_0.21.0_linux_arm64.tar.gz"
      sha256 "1bdca94fb9611a59544fc0803c2259e78b32e37aab0ff1b5ab901736642e52b3"
      define_method(:install) do
        bin.install "mycelium"
      end
    end
  end

  test do
    system "#{bin}/mycelium --version"
  end
end
