# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mycelium < Formula
  desc "Shared agent memory across AI coding agents and machines"
  homepage "https://github.com/FacileStudio/Mycelium"
  version "0.16.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.16.1/Mycelium_0.16.1_darwin_amd64.tar.gz"
      sha256 "4d2a3879143b1380b774eb93bd94812053014e6e2d36010d0c9c6e3742518e02"

      define_method(:install) do
        bin.install "mycelium"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.16.1/Mycelium_0.16.1_darwin_arm64.tar.gz"
      sha256 "e22c748613035603473f63520ab2a5bee1a81babda1642501483e2831140753c"

      define_method(:install) do
        bin.install "mycelium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.16.1/Mycelium_0.16.1_linux_amd64.tar.gz"
      sha256 "15ae43d937bb3b17b931e601a7a49f9886ebddfa686de946959f8a46e92d3de3"
      define_method(:install) do
        bin.install "mycelium"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.16.1/Mycelium_0.16.1_linux_arm64.tar.gz"
      sha256 "73f6099197b8d0d1d48f057b82f1287ac94af2b6926f1a844e03d5a4f4416efb"
      define_method(:install) do
        bin.install "mycelium"
      end
    end
  end

  test do
    system "#{bin}/mycelium --version"
  end
end
