# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mycelium < Formula
  desc "Shared agent memory across AI coding agents and machines"
  homepage "https://github.com/FacileStudio/Mycelium"
  version "0.12.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.12.0/Mycelium_0.12.0_darwin_amd64.tar.gz"
      sha256 "fa73296f205a05b8f21b0e173b392a1d31df6a8fe7d3c0fe9b193743f002b5ed"

      define_method(:install) do
        bin.install "mycelium"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.12.0/Mycelium_0.12.0_darwin_arm64.tar.gz"
      sha256 "6fd499869b5936d53a02b086bb8ccca4f942789873cb107d3031ef8da9a297f5"

      define_method(:install) do
        bin.install "mycelium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.12.0/Mycelium_0.12.0_linux_amd64.tar.gz"
      sha256 "1d26925aa2f0d5f40e2df53bc409752faa6ca089d6d80624ba81d95eec0117a2"
      define_method(:install) do
        bin.install "mycelium"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/Mycelium/releases/download/v0.12.0/Mycelium_0.12.0_linux_arm64.tar.gz"
      sha256 "1127d3ae2c173c3471ea54605c1d1a24c052a8f7192828cddd139273e6459529"
      define_method(:install) do
        bin.install "mycelium"
      end
    end
  end

  test do
    system "#{bin}/mycelium --version"
  end
end
