# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nacelle < Formula
  desc "Terminal coding agent — the human harness for the nacelle SDK"
  homepage "https://github.com/FacileStudio/nacelle-tui"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v0.2.0/nacelle-tui_0.2.0_darwin_amd64.tar.gz"
      sha256 "638d0262033d54d678c9403bd3acbd1a0c3f4f6f1579cef8acdc6eab4f5b37ba"

      define_method(:install) do
        bin.install "nacelle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v0.2.0/nacelle-tui_0.2.0_darwin_arm64.tar.gz"
      sha256 "812c22c7b7a74bc91035783b2fc358ade161aaaf0b19582ecc97d91690ce78b9"

      define_method(:install) do
        bin.install "nacelle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v0.2.0/nacelle-tui_0.2.0_linux_amd64.tar.gz"
      sha256 "5e9241f5240802e934f123c6811ec3500b336054db5ef91a5defcbc66a06da88"
      define_method(:install) do
        bin.install "nacelle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v0.2.0/nacelle-tui_0.2.0_linux_arm64.tar.gz"
      sha256 "f9f6333dd3d32c42f6b65df8eccfecb54595a1614edaf22e214fb7899803f600"
      define_method(:install) do
        bin.install "nacelle"
      end
    end
  end

  test do
    system "#{bin}/nacelle -version"
  end
end
