# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nacelle < Formula
  desc "Terminal coding agent — the human harness for the nacelle SDK"
  homepage "https://github.com/FacileStudio/nacelle-tui"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v0.1.0/nacelle-tui_0.1.0_darwin_amd64.tar.gz"
      sha256 "b3ed5e079c62f9a0e80b349a5b30b5cfa3e29b317892e871055d2b7c17fa9f4a"

      define_method(:install) do
        bin.install "nacelle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v0.1.0/nacelle-tui_0.1.0_darwin_arm64.tar.gz"
      sha256 "65fffff666b8363869f86242ec3dcce342a154ffdfccbb18040493ec87b042e5"

      define_method(:install) do
        bin.install "nacelle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v0.1.0/nacelle-tui_0.1.0_linux_amd64.tar.gz"
      sha256 "5a09f57334750ebe6d4b2abec4bc54a3681cc3fe7bdfc5376fb019c6ee1bdbc8"
      define_method(:install) do
        bin.install "nacelle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/nacelle-tui/releases/download/v0.1.0/nacelle-tui_0.1.0_linux_arm64.tar.gz"
      sha256 "bb438bd2e8979bc19954661c206d5b3796e5e8f4d52cb26239d8ba0e0efc8910"
      define_method(:install) do
        bin.install "nacelle"
      end
    end
  end

  test do
    system "#{bin}/nacelle -version"
  end
end
