# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ruche < Formula
  desc "Shared agent memory across AI coding agents and machines"
  homepage "https://github.com/FacileStudio/Ruche"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FacileStudio/Ruche/releases/download/v0.1.0/Ruche_0.1.0_darwin_amd64.tar.gz"
      sha256 "f936fc16c7c2b701b13ad3a41e1b8b5f165945ac9e0cdc2191b470cea0e194df"

      define_method(:install) do
        bin.install "ruche"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FacileStudio/Ruche/releases/download/v0.1.0/Ruche_0.1.0_darwin_arm64.tar.gz"
      sha256 "d589b4764c946b416652d1c8e2da06651f74975ec1df2ca0eed433ac2dc95760"

      define_method(:install) do
        bin.install "ruche"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/Ruche/releases/download/v0.1.0/Ruche_0.1.0_linux_amd64.tar.gz"
      sha256 "b8350bab6d5ad01fb3f604b23e3f54227befb3007bfeff301decba0f86299761"
      define_method(:install) do
        bin.install "ruche"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FacileStudio/Ruche/releases/download/v0.1.0/Ruche_0.1.0_linux_arm64.tar.gz"
      sha256 "08f8a88e21ad2ebc26ca7d0fe62ad0a38ec1186f16318e609464a20142893420"
      define_method(:install) do
        bin.install "ruche"
      end
    end
  end

  test do
    system "#{bin}/ruche --version"
  end
end
